apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: aws-sqs-auth
  namespace: default
spec:
  podIdentity:
    provider: aws # Tells KEDA to use the attached IRSA role
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: aws-sqs-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: ai-worker
  minReplicaCount: 0 # Scale to 0 when idle
  maxReplicaCount: 50 # Prevent scaling infinitely
  pollingInterval: 10 # Check queue every 10 seconds
  cooldownPeriod: 60  # Wait 60s before scaling back down to 0
  triggers:
  - type: aws-sqs-queue
    authenticationRef:
      name: aws-sqs-auth
    metadata:
      queueURL: "https://sqs.ap-south-1.amazonaws.com/032080729357/ai-task-queue"
      queueLength: "5" # Target: 1 pod for every 5 messages
      awsRegion: "ap-south-1"
