apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fraud-model-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://gitlab.com/my-org/mlops-manifests.git'
    targetRevision: HEAD
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ml-workloads
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
