apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
images:
  - name: PLACEHOLDER
    newName: 496203436083.dkr.ecr.ap-south-1.amazonaws.com/mlops-fraud-model
